name: Build and Deploy to release

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: package-version
      run: node -p -e '`PACKAGE_VERSION=${require("./angular/package.json").version}`' >> $GITHUB_ENV
     
    - name: Install dependencies
      working-directory: ./angular
      run: npm install

    - name: Run tests
      working-directory: ./angular
      run: npm run test:headless

    - name: Build
      working-directory: ./angular
      run: npm run build:prod

   